account_id = "d10780b663ebaff9391d2c32c3cc8dc9"
name = "fedi-status-cf-worker"
main = "./src/worker/index.ts"
compatibility_flags = [ "streams_enable_constructors" ]
compatibility_date = "2021-09-29"
workers_dev = true
# npx --no -- wrangler kv:namespace create cf-worker-status-page-pro
kv_namespaces = [ { binding = "KV_STORE", id = "af37617e377142febc24cd6f986a5203" } ]

[site]
bucket = "./dist/client"

[dev]
port = 3000

[env.production]
kv_namespaces = [ { binding = "KV_STORE", id = "af37617e377142febc24cd6f986a5203" } ]

[env.production.triggers]
# https://crontab.guru/#*/2_*_*_*_*
crons = [ "* * * * *" ]
