import type { Config } from './types'

export const config: Config = {
  settings: {
    title: '페디버스 상태',
    url: 'https://status.fediverses.kr',
    displayDays: 90,
    collectResponseTimes: true,
  },
  monitors: [
    {
      id: 'bsky-social',
      url: 'https://bsky.app/',
      description: 'Bluesky (SocialApp XRPC)',
      followRedirect: false,
    },
    {
      id: 'fed-brid-gy',
      url: 'https://fed.brid.gy/',
      description: 'Bridgy Fed',
      followRedirect: false,
    },
    {
      id: 'planet-moe',
      url: 'https://planet.moe/',
      description: '플래닛',
      followRedirect: false,
    },
    {
      id: 'qdon-space',
      url: 'https://qdon.space/',
      description: '큐돈',
      followRedirect: false,
    },
    {
      id: 'jmm-kr',
      url: 'https://jmm.kr/',
      description: '즘',
      followRedirect: false,
    },
    {
      id: 'toot-funami-tech',
      url: 'https://toot.funami.tech/',
      description: '유루툿',
      followRedirect: false,
    },
    {
      id: 'uri-life',
      url: 'https://uri.life/',
      description: '우리인생',
      followRedirect: false,
    },
    {
      id: 'maratang-life',
      url: 'https://maratang.life/',
      description: '마라탕.인생',
      followRedirect: false,
    },
    {
      id: 'kurry-social',
      url: 'https://kurry.social/',
      description: '커리',
      followRedirect: false,
    },
    {
      id: 'occm-cc',
      url: 'https://occm.cc/',
      description: '자커마스',
      followRedirect: false,
    },
    {
      id: 'pointless-chat',
      url: 'https://pointless.chat/',
      description: '포인트리스',
      followRedirect: false,
    },
    {
      id: 'muri-network',
      url: 'https://muri.network/',
      description: '무리 네트워크',
      followRedirect: false,
    },
    {
      id: 'netsphere-one',
      url: 'https://netsphere.one/',
      description: '넷스피어 원',
      followRedirect: false,
    },
    {
      id: 'mastodon-mnetwork-co-kr',
      url: 'https://mastodon.mnetwork.co.kr/',
      description: '엠네트워크 마스토돈',
      followRedirect: false,
    },
    {
      id: 'mustard-blog',
      url: 'https://mustard.blog/',
      description: '머스타드',
      followRedirect: false,
    },
    {
      id: 't-chadole-com',
      url: 'https://t.chadole.com/',
      description: '차돌이',
      followRedirect: false,
    },
    {
      id: 'krpgpub-net',
      url: 'https://krpgpub.net/',
      description: '알피지 주점',
      followRedirect: false,
    },
    {
      id: 'bakedbean-xyz',
      url: 'https://bakedbean.xyz/',
      description: '슈퍼마-켙',
      followRedirect: false,
    },
    {
      id: 'kono-pub',
      url: 'https://kono.pub/',
      description: '콘오.펍',
      followRedirect: false,
    },
    {
      id: 'trpg-o-xyz',
      url: 'https://trpg-o.xyz/',
      description: '티알피지',
      followRedirect: false,
    },
    {
      id: 'smore',
      url: 'https://s.mysw.moe/',
      description: "S'More",
      followRedirect: false,
    },
    {
      id: 'catswords-social',
      url: 'https://catswords.social/',
      description: '캐츠워즈 콜로세움',
      followRedirect: false,
    },
    {
      id: 'town-voyager-blue',
      url: 'https://town.voyager.blue/',
      description: '페일 블루 보이저 네트워크',
      followRedirect: false,
    },
    {
      id: 'duk-space',
      url: 'https://duk.space/',
      description: '덕스페이스',
      followRedirect: false,
    },
    {
      id: 'misskey-kr',
      url: 'https://misskey.kr/',
      description: '미스키한국',
      followRedirect: false,
    },
    {
      id: 'k-lapy-link',
      url: 'https://k.lapy.link/',
      description: '키라링',
      followRedirect: false,
    },
    {
      id: 'buttersc-one',
      url: 'https://buttersc.one/',
      description: '버터스콘',
      followRedirect: false,
    },
    {
      id: 'masost-one',
      url: 'https://masost.one/',
      description: '맛소스통',
      followRedirect: false,
    },
    {
      id: 'hoto-moe',
      url: 'https://hoto.moe/',
      description: '호토모에',
      followRedirect: false,
    },
    {
      id: 'kokonect-link',
      url: 'https://kokonect.link/',
      description: '코코넥트',
      followRedirect: false,
    },
    {
      id: 'nekoplanet-xyz',
      url: 'https://nekoplanet.xyz/',
      description: '고양이별',
      followRedirect: false,
    },
    {
      id: 'daepi-so',
      url: 'https://daepi.so/',
      description: '대피소',
      followRedirect: false,
    },
    {
      id: 'yodangang-express',
      url: 'https://yodangang.express/',
      description: '요단강 익스프레스',
      followRedirect: false,
    },
  ],
  // monitorsCsvUrl: 'https://docs.google.com',
}
