import type { Config } from './types'

export const config: Config = {
  settings: {
    title: '페디버스 상태',
    url: 'https://status.fediverses.kr',
    displayDays: 90,
    collectResponseTimes: true,
  },
  monitors: [
    {
      id: 'bsky-social',
      url: 'https://bsky.app/',
      name: 'Bluesky (SocialApp XRPC)',
      followRedirect: true,
    },
    {
      id: 'fed-brid-gy',
      url: 'https://fed.brid.gy/',
      name: 'Bridgy Fed',
      followRedirect: true,
    },
    {
      id: 'planet-moe',
      url: 'https://planet.moe/',
      name: '플래닛',
      followRedirect: true,
    },
    {
      id: 'qdon-space',
      url: 'https://qdon.space/',
      name: '큐돈',
      followRedirect: true,
    },
    {
      id: 'jmm-kr',
      url: 'https://jmm.kr/',
      name: '즘',
      followRedirect: true,
    },
    {
      id: 'toot-funami-tech',
      url: 'https://toot.funami.tech/',
      name: '유루툿',
      followRedirect: true,
    },
    {
      id: 'uri-life',
      url: 'https://uri.life/',
      name: '우리인생',
      followRedirect: true,
    },
    {
      id: 'maratang-life',
      url: 'https://maratang.life/',
      name: '마라탕.인생',
      followRedirect: true,
    },
    {
      id: 'kurry-social',
      url: 'https://kurry.social/',
      name: '커리',
      followRedirect: true,
    },
    {
      id: 'occm-cc',
      url: 'https://occm.cc/',
      name: '자커마스',
      followRedirect: true,
    },
    {
      id: 'pointless-chat',
      url: 'https://pointless.chat/',
      name: '포인트리스',
      followRedirect: true,
    },
    {
      id: 'muri-network',
      url: 'https://muri.network/',
      name: '무리 네트워크',
      followRedirect: true,
    },
    {
      id: 'netsphere-one',
      url: 'https://netsphere.one/',
      name: '넷스피어 원',
      followRedirect: true,
    },
    {
      id: 'mastodon-mnetwork-co-kr',
      url: 'https://mastodon.mnetwork.co.kr/',
      name: '엠네트워크 마스토돈',
      followRedirect: true,
    },
    {
      id: 'mustard-blog',
      url: 'https://mustard.blog/',
      name: '머스타드',
      followRedirect: true,
    },
    {
      id: 't-chadole-com',
      url: 'https://t.chadole.com/',
      name: '차돌이',
      followRedirect: true,
    },
    {
      id: 'krpgpub-net',
      url: 'https://krpgpub.net/',
      name: '알피지 주점',
      followRedirect: true,
    },
    {
      id: 'bakedbean-xyz',
      url: 'https://bakedbean.xyz/',
      name: '슈퍼마-켙',
      followRedirect: true,
    },
    {
      id: 'kono-pub',
      url: 'https://kono.pub/',
      name: '콘오.펍',
      followRedirect: true,
    },
    {
      id: 'trpg-o-xyz',
      url: 'https://trpg-o.xyz/',
      name: '티알피지',
      followRedirect: true,
    },
    {
      id: 'smore',
      url: 'https://s.mysw.moe/',
      name: "S'More",
      followRedirect: true,
    },
    {
      id: 'catswords-social',
      url: 'https://www.catswords.social/',
      name: '캐츠워즈 콜로세움',
      followRedirect: true,
    },
    {
      id: 'town-voyager-blue',
      url: 'https://town.voyager.blue/',
      name: '페일 블루 보이저 네트워크',
      followRedirect: true,
    },
    {
      id: 'duk-space',
      url: 'https://duk.space/',
      name: '덕스페이스',
      followRedirect: true,
    },
    {
      id: 'misskey-kr',
      url: 'https://misskey.kr/',
      name: '미스키한국',
      followRedirect: true,
    },
    {
      id: 'k-lapy-link',
      url: 'https://k.lapy.link/',
      name: '키라링',
      followRedirect: true,
    },
    {
      id: 'buttersc-one',
      url: 'https://buttersc.one/',
      name: '버터스콘',
      followRedirect: true,
    },
    {
      id: 'masost-one',
      url: 'https://masost.one/',
      name: '맛소스통',
      followRedirect: true,
    },
    {
      id: 'hoto-moe',
      url: 'https://hoto.moe/',
      name: '호토모에',
      followRedirect: true,
    },
    {
      id: 'kokonect-link',
      url: 'https://kokonect.link/',
      name: '코코넥트',
      followRedirect: true,
    },
    {
      id: 'nekoplanet-xyz',
      url: 'https://nekoplanet.xyz/',
      name: '고양이별',
      followRedirect: true,
    },
    {
      id: 'daepi-so',
      url: 'https://daepi.so/',
      name: '대피소',
      followRedirect: true,
    },
    {
      id: 'yodangang-express',
      url: 'https://yodangang.express/',
      name: '요단강 익스프레스',
      followRedirect: true,
    },
    {
      id: 'kitsunesoba',
      url: 'https://kitsunesoba.com/',
      name: '키츠네소바🦊',
      followRedirect: true,
    },
    
  ],
  // monitorsCsvUrl: 'https://docs.google.com',
}
